language: python
python:
  - "3.5"
  - "3.6"

virtualenv:
  system_site_packages: true

#Prer-testing installs
intsall:
  - pip install .

services:
  - docker

# Scripts to be run such as tests
beforer_script:
  - echo "no tests"

script:
  - docker --verion # print the version for logging
  - docker build -t wpscraper .
  - docker tag wpscraper lovesantacruz/wpscraper:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lovesantacruz/wpscraper
